# Generated by Django 5.1 on 2024-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Dimensions",
            field=models.CharField(default="Dimensions not available", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default="Color not specified", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="item_type",
            field=models.CharField(default="Not specified", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="state_of_origin",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
